language: python
sudo: required
services:
  - docker
env:
  global:
  - DOCKER_EMAIL=docker@hydrachain.com
  - DOCKER_USERNAME=hydrachain
  - secure: "V1tvKjhqsKqB1I5mf76v2PjnZtsu+tjhWxCw4mbwOERTj1EI3wKm4vijWnaWHoKx6VLcIM7vzGffKH7fhtKG8ChWP3H5QaaQMPYJ2GPYqTOZyPnSQ/ljl5PxMOPssQuqW1d8llvB5AYMrP5aVBBtysT5d+412f0Fw27KhBDzXdy5M+5/yHiOy1LD1Gb5fx5gvao3ljytDhpTO5KcJL2przQQQGYyRCyEeWNyTi04b/Xk0G9uzvVQOIIdA4BV2JDKhzStpWCkxt+HjP0znjJQprU7ieDeapGzvj0eNoRs4w05USbc2ChQh/+i2K+ttOdO/Fku5uFBfah1yMeEWsD3LgVB6kdgK4TK7rq6CU+kcHzqYZjWtbCOKmL0kTDZYgemNyeTh4ENSmWNBZ3KJRzWlXuwzRYfygLYXMaMrOZbPQj6J65VlLpFwSxbczToEF21PLu5r8cIV1x9aoDC2jJ86anCkmPa95SYlj9g8eZdtmIPslbY5bpnjt0+tCSRsCIGu28jsQdnvwLT8ZlIyLLFR4uGLKJb8lh6Pq6PuhNMIs5fp4k+T5KPhhJIpkLvZWFIm6L5BK/w0GiDXrA6tPEo7knI8fQpOmg5TcrL3yTieuSpn/zUAwlgWgImP44pTWDT370JD3E+6ZnHEbKYSZM/cTcEPpBe703sumPpcKT/mPY="
  matrix:
  - TOXENV=py27
addons:
  apt:
    packages:
    - libgmp3-dev
install:
  - pip install tox
  - pip install coveralls
script: tox -- --ignore hydrachain/tests/test_sim_failures.py --ignore hydrachain/tests/test_sim_syncing.py
after_success: 
  - coveralls
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t hydrachain/hydrachain:${TRAVIS_TAG:-develop} .
  - docker push hydrachain/hydrachain:${TRAVIS_TAG:-develop}
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: "vO6kAkkpdqQz2+Le7aowcIkYHyvQzuNaL35c8ciHzmT2VdeGeCsDBGyJ8RYqITQruwfVzUsKsNjfCXBTcYan3e1vPpG9KKrkxB/Zy6KcNJmd+SL9n2tB6TVFr1ojxnRJgIzFBxbA1FnyY0aodwnMW2bJBlKxFIKJiKVjK6GGDl11wrMsudFFnvs3LkrPO9tr1plmN1xvVTNLzy0UmHjx6lmtjtZ/HMbx635WnFj5NnzdeMK07XD59HEuOYVvQ7BQua2cuCevFbXmSAxHJsDPZuhzYHkEfj+jPhKbS1MyTqD5W72ex2oPRmPlvvnOn01750IkSFSyO0lnZIv1wJuZ3+Y+49Q5XrFBAsuC4bqk1uOVL5hU37b2oDBIunJLQYEP1tn7TibVbv51iOolzx193tRR7KcbyU+pIqdP4a6rWDXT+PRada2JemX/Bx4G5hn9dXc4SmLP0+t7lcYpe/fTLQCGYsLNBbJv7iJdTuOeySX8Dlq9GYBMGreilDwIp5T4eqT4mhc25ZaXRel2HdqQSzie8SM88Sempn1V3uQkvQSUZ/PcwDwrG8wLK37BubaW0qVAZ5Zfkv1Q+pnVd7OkTEU+GgdOST6H3WGKVSO0fs/vLFYhQN0273IqM3Uuh3+s5h/sbGWfXqPMS8lu6febpglBCAxvkgKjwQ0in2S3Fo8="
  on:
    tags: true
    repo: HydraChain/hydrachain
    branch: develop
  distributions: "sdist bdist_wheel"
after_deploy:
  - docker tag hydrachain/hydrachain:$TRAVIS_TAG hydrachain/hydrachain:latest
  - docker push hydrachain/hydrachain:latest
